name: 🚀 Deploy to Oracle Cloud

on:
  push:
    branches:
      - main  # or master if you use that

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 144.24.158.5 >> ~/.ssh/known_hosts

      - name: Deploy to Oracle Cloud
        run: |
          ssh ubuntu@144.24.158.5 << 'EOF'
          cd ~/markit-server
          git fetch origin main
          git reset --hard origin/main
          npm install --production
          pm2 restart markit-server || pm2 start index.js --name markit-server
          pm2 save
          EOF
